### ISSUE TITLE
Android build fails on OSX and Linux

### ISSUE THREAD

**Issue by adrianbrink** [paritytech/native-signer#12]
```
➜  native-signer git:(master) ✗ react-native run-android
Starting JS server...
Running /home/avo/Android/Sdk/platform-tools/adb -s 192.168.56.101:5555 reverse tcp:8081 tcp:8081
Building and installing the app on the device (cd android && ./gradlew installDebug)...
Incremental java compilation is an incubating feature.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> NDK not configured. 
  Download it with SDK manager.)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 4.122 secs
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/android-setup.html

(node:1275) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: Cannot read property 'message' of undefined
```

So running for iOS works but on Android this fails on OSX and Ubuntu.

Also, in order for it to work on Ubuntu you have to comment out the ```brew --prefix``` line in ```./create_standalone_ndk```.

I have checked the jniLibs contains the correct files for the NDK.

**Comment by debris** [comment]
The error message you pasted looks like a problem with your environment, not build native-signer build script. I have the following NDK related env variables set:

```
export ANDROID_NDK="/usr/local/opt/android-ndk"
export NDK_HOME="/usr/local/opt/android-ndk"
```

**Comment by adrianbrink** [comment]
```
echo $ANDROID_NDK : /home/avo/Android/Sdk/ndk-bundle
echo $NDK_HOME : /home/avo/Android/Sdk/ndk-bundle
```

Both on Ubuntu and OSX. Are you using the native virtual device, because I am using genymotion.

**Comment by debris** [comment]
I'm using Intel Atom. I have very basic configuration, I just followed all steps from: https://facebook.github.io/react-native/docs/getting-started.html

**Comment by adrianbrink** [comment]
mh, I'll test it again tomorrow and set it up from scratch :-)

**Comment by debris** [comment]
ok, so I think we have figured out the solution. When you start Android Studio project for the first time, it creates `local.properties` in `android/` directory. This file is gitignored, so it's not a part of the repo

<img width="650" alt="screen shot 2017-03-24 at 17 52 20" src="https://cloud.githubusercontent.com/assets/2613714/24291368/333e3798-10bb-11e7-99f9-085be8c47e01.png">

**Comment by tomusdrw** [comment]
Should be fixed now (README updated as well). @adrianbrink please re-open if it still occurs for you.

**Comment by adrianbrink** [comment]
Mh, I'm not entirely sure whether I should reopen this. :-)

It still doesn't work, but I think I know what the problem is. The images used by react-native (Intel Atom x86_64) are not available on the Ubuntu installation by default. 

You have to install [HAXM](https://software.intel.com/en-us/blogs/2012/03/12/how-to-start-intel-hardware-assisted-virtualization-hypervisor-on-linux-to-speed-up-intel-android-x86-emulator) and following these two [links](https://askubuntu.com/questions/600727/replacement-for-haxm-on-ubuntu-says-intel-x86-emulator-accelerator-is-not-comp) and the hopefully the correct images will show up.

I am trying that now and will let you know whether it works.

**Comment by adrianbrink** [comment]
It's fixed. I think it was most likely due to not having HAXM installed. Should we add it to the README?
