### ISSUE TITLE
account seeds should be encrypted using pin, before saving in secure store

### ISSUE THREAD

**Issue by debris** [paritytech/native-signer#19]

**Comment by tomusdrw** [comment]
That sounds like a cool use case for that feature:
https://developer.android.com/training/articles/keystore.html#UserAuthentication
Not sure if there are react-native wrappers though.

Maybe we could use this?
https://github.com/oblador/react-native-keychain

**Comment by debris** [comment]
we already use keychain. Second encryption is just additional layer of security ;)
