### ISSUE TITLE
"Done" button on QR Code screen is unnecessary

### ISSUE THREAD

**Issue by tomusdrw** [paritytech/native-signer#2]
Currently you have "Back" and "Done" I think just "Back" is enough.
(Also the title could be more descriptive and address + identicon should be displayed)

![screenshot_20170322-120420](https://cloud.githubusercontent.com/assets/581548/24194843/dc251158-0ef7-11e7-8c2e-b2f4656dd412.png)

**Comment by debris** [comment]
They actually do different things. Back let's you go back to the previous screen while Done let's you scan another qr code

**Comment by tomusdrw** [comment]
Yeah I know. Actually "Back" takes you to account page and "Done" takes you to account list. But it doesn't make any sens to me and I was just confused about which one I should click.

**Comment by debris** [comment]
ah, you are right. It made much more sense when we could chose account to sign a transaction. I will remove `Back` button

**Comment by tomusdrw** [comment]
Why not "Done" I think it's better to go back to the account, and then when #7 is in you can go directly to the list as well.

"Back" seems like a good think to consistently have in the same place.

**Comment by debris** [comment]
ah, wait... that's a qr code with account details, right? I thought it is signed transaction 😂
