### ISSUE TITLE
Make sure that proper random source is used

### ISSUE THREAD

**Issue by tomusdrw** [paritytech/native-signer#36]
Related https://github.com/paritytech/wordlist/issues/2

There is no `Buffer` nor `Uint8Array` available, so we need something that works in pure JS and has good enough entropy.

**Comment by debris** [comment]
so, what about #37? does it work?

**Comment by tomusdrw** [comment]
Yes, it works but falls back to:
https://github.com/paritytech/wordlist/blob/master/index.js#L60

So it uses `Math.random()` which is not crypto-secure:
http://stackoverflow.com/questions/5651789/is-math-random-cryptographically-secure

**Comment by debris** [comment]
so I think, we should generate random words / numbers on rust side
