### ISSUE TITLE
android keypad doesn't automatically fold away when pin is entered

### ISSUE THREAD

**Issue by debris** [paritytech/native-signer#46]

**Comment by tomusdrw** [comment]
Happens when signing transaction (also when going back from "Enter PIN" dialog). Doesn't happen on new Accounts / Change PIN though.

**Comment by debris** [comment]
@tomusdrw could you try to fix it? I really can't reproduce this on iOS / emulator

**Comment by tomusdrw** [comment]
Sure, will have a look.
