### ISSUE TITLE
Buttons don't give you visual feedback on tap

### ISSUE THREAD

**Issue by tomusdrw** [paritytech/native-signer#6]
Especially the green ones, you cannot tell if the tap was registered by the app.

**Comment by debris** [comment]
They supposed be the default android buttons ;) I'll see what I can do

**Comment by tomusdrw** [comment]
The buttons on the dark bars work ok, only the green/red ones in the middle screen seem broken (no feedback on click).

**Comment by tomusdrw** [comment]
Actually the feedback works correctly but is barely visible on my device.
