### ISSUE TITLE
"Accounts" button on the dark bar should always take you to accounts list

### ISSUE THREAD

**Issue by tomusdrw** [paritytech/native-signer#7]
Currently if you open some account this button doesn't do anything.

**Comment by debris** [comment]
isn't it the expected behaviour? please check facebook or instagram apps :)

**Comment by tomusdrw** [comment]
It is different, cause when you switch the context from "List view" to "Detailed view" those buttons disappear, but in our App it's still there but it doesn't do anything.
So clicking the same button has different result depending on the context in which you're actually in and IMHO it's not a good ux.

**Comment by debris** [comment]
Ok, so I've checked and those apps (at least on iOS) behave in two ways:

- if you press tab button, when in detailed view, it takes you back to the first screen
- If you press tab button of a different view it switches you to it, if you press your tab button after, you are again in detailed view

I will create an issue upstream, and maybe author of this library will fix it ;)

**Comment by tomusdrw** [comment]
Seems that it works correctly for me now. Not sure if anything changed.
