### ISSUE TITLE
Build fails on Linux

### ISSUE THREAD

**Issue by adrianbrink** [paritytech/native-signer#9]
the build.rs script for rust-crypto has a hardcoded dependency on OSX.

[here](https://github.com/debris/rust-crypto/blob/master/build.rs#L12) it assumes that the folder name includes 'darwin' whereas on linux it is 'linux'. :-)

**Comment by adrianbrink** [comment]
The easy fix is to symlink the linux folder to a newly created darwin folder to match OSX.

**Comment by debris** [comment]
right... I'm pretty sure I've already fixed this issue for another package. I will try to find it and backport the fix

**Comment by debris** [comment]
here it is https://github.com/paritytech/rust-secp256k1/commit/0cca5174cffc6e8896c9098ba448db9faf9faa36 ! backporting now!
